//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WealthGrowthCreditVerification.CompuscanClient {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServices/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private stackTraceElement[][] suppressedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stackTrace", typeof(stackTraceElement), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public stackTraceElement[][] suppressed {
            get {
                return this.suppressedField;
            }
            set {
                this.suppressedField = value;
                this.RaisePropertyChanged("suppressed");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServices/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServices/")]
    public partial class NormalEnqRequestParamsType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pUsrnmeField;
        
        private string pPasswrdField;
        
        private string pVersionField;
        
        private string pOriginField;
        
        private string pOrigin_VersionField;
        
        private string pInput_FormatField;
        
        private string pTransactionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string pUsrnme {
            get {
                return this.pUsrnmeField;
            }
            set {
                this.pUsrnmeField = value;
                this.RaisePropertyChanged("pUsrnme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pPasswrd {
            get {
                return this.pPasswrdField;
            }
            set {
                this.pPasswrdField = value;
                this.RaisePropertyChanged("pPasswrd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string pVersion {
            get {
                return this.pVersionField;
            }
            set {
                this.pVersionField = value;
                this.RaisePropertyChanged("pVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string pOrigin {
            get {
                return this.pOriginField;
            }
            set {
                this.pOriginField = value;
                this.RaisePropertyChanged("pOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string pOrigin_Version {
            get {
                return this.pOrigin_VersionField;
            }
            set {
                this.pOrigin_VersionField = value;
                this.RaisePropertyChanged("pOrigin_Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pInput_Format {
            get {
                return this.pInput_FormatField;
            }
            set {
                this.pInput_FormatField = value;
                this.RaisePropertyChanged("pInput_Format");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string pTransaction {
            get {
                return this.pTransactionField;
            }
            set {
                this.pTransactionField = value;
                this.RaisePropertyChanged("pTransaction");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webServices/", ConfigurationName="CompuscanClient.NormalSearchStreamService")]
    public interface NormalSearchStreamService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WealthGrowthCreditVerification.CompuscanClient.PingServerResponse PingServer(WealthGrowthCreditVerification.CompuscanClient.PingServerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WealthGrowthCreditVerification.CompuscanClient.PingServerResponse> PingServerAsync(WealthGrowthCreditVerification.CompuscanClient.PingServerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WealthGrowthCreditVerification.CompuscanClient.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamResponse DoNormalEnquiryStream(WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamResponse> DoNormalEnquiryStreamAsync(WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WealthGrowthCreditVerification.CompuscanClient.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestResponse DoNormalEnquiryStreamTest(WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestResponse> DoNormalEnquiryStreamTestAsync(WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingServer", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class PingServerRequest {
        
        public PingServerRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingServerResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class PingServerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public PingServerResponse() {
        }
        
        public PingServerResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoNormalEnquiryStream", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class DoNormalEnquiryStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WealthGrowthCreditVerification.CompuscanClient.NormalEnqRequestParamsType request;
        
        public DoNormalEnquiryStreamRequest() {
        }
        
        public DoNormalEnquiryStreamRequest(WealthGrowthCreditVerification.CompuscanClient.NormalEnqRequestParamsType request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoNormalEnquiryStreamResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class DoNormalEnquiryStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[][] @return;
        
        public DoNormalEnquiryStreamResponse() {
        }
        
        public DoNormalEnquiryStreamResponse(byte[][] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webServices/")]
    public partial class transReplyStreamClass : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool transactionCompletedField;
        
        private string errorCodeField;
        
        private string errorStringField;
        
        private byte[][] retDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool transactionCompleted {
            get {
                return this.transactionCompletedField;
            }
            set {
                this.transactionCompletedField = value;
                this.RaisePropertyChanged("transactionCompleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string errorString {
            get {
                return this.errorStringField;
            }
            set {
                this.errorStringField = value;
                this.RaisePropertyChanged("errorString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("retData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[][] retData {
            get {
                return this.retDataField;
            }
            set {
                this.retDataField = value;
                this.RaisePropertyChanged("retData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoNormalEnquiryStreamTest", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class DoNormalEnquiryStreamTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WealthGrowthCreditVerification.CompuscanClient.NormalEnqRequestParamsType request;
        
        public DoNormalEnquiryStreamTestRequest() {
        }
        
        public DoNormalEnquiryStreamTestRequest(WealthGrowthCreditVerification.CompuscanClient.NormalEnqRequestParamsType request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoNormalEnquiryStreamTestResponse", WrapperNamespace="http://webServices/", IsWrapped=true)]
    public partial class DoNormalEnquiryStreamTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WealthGrowthCreditVerification.CompuscanClient.transReplyStreamClass @return;
        
        public DoNormalEnquiryStreamTestResponse() {
        }
        
        public DoNormalEnquiryStreamTestResponse(WealthGrowthCreditVerification.CompuscanClient.transReplyStreamClass @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NormalSearchStreamServiceChannel : WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NormalSearchStreamServiceClient : System.ServiceModel.ClientBase<WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService>, WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService {
        
        public NormalSearchStreamServiceClient() {
        }
        
        public NormalSearchStreamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NormalSearchStreamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NormalSearchStreamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NormalSearchStreamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WealthGrowthCreditVerification.CompuscanClient.PingServerResponse WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService.PingServer(WealthGrowthCreditVerification.CompuscanClient.PingServerRequest request) {
            return base.Channel.PingServer(request);
        }
        
        public bool PingServer() {
            WealthGrowthCreditVerification.CompuscanClient.PingServerRequest inValue = new WealthGrowthCreditVerification.CompuscanClient.PingServerRequest();
            WealthGrowthCreditVerification.CompuscanClient.PingServerResponse retVal = ((WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService)(this)).PingServer(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WealthGrowthCreditVerification.CompuscanClient.PingServerResponse> WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService.PingServerAsync(WealthGrowthCreditVerification.CompuscanClient.PingServerRequest request) {
            return base.Channel.PingServerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WealthGrowthCreditVerification.CompuscanClient.PingServerResponse> PingServerAsync() {
            WealthGrowthCreditVerification.CompuscanClient.PingServerRequest inValue = new WealthGrowthCreditVerification.CompuscanClient.PingServerRequest();
            return ((WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService)(this)).PingServerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamResponse WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService.DoNormalEnquiryStream(WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamRequest request) {
            return base.Channel.DoNormalEnquiryStream(request);
        }
        
        public byte[][] DoNormalEnquiryStream(WealthGrowthCreditVerification.CompuscanClient.NormalEnqRequestParamsType request) {
            WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamRequest inValue = new WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamRequest();
            inValue.request = request;
            WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamResponse retVal = ((WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService)(this)).DoNormalEnquiryStream(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamResponse> WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService.DoNormalEnquiryStreamAsync(WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamRequest request) {
            return base.Channel.DoNormalEnquiryStreamAsync(request);
        }
        
        public System.Threading.Tasks.Task<WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamResponse> DoNormalEnquiryStreamAsync(WealthGrowthCreditVerification.CompuscanClient.NormalEnqRequestParamsType request) {
            WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamRequest inValue = new WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamRequest();
            inValue.request = request;
            return ((WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService)(this)).DoNormalEnquiryStreamAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestResponse WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService.DoNormalEnquiryStreamTest(WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestRequest request) {
            return base.Channel.DoNormalEnquiryStreamTest(request);
        }
        
        public WealthGrowthCreditVerification.CompuscanClient.transReplyStreamClass DoNormalEnquiryStreamTest(WealthGrowthCreditVerification.CompuscanClient.NormalEnqRequestParamsType request) {
            WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestRequest inValue = new WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestRequest();
            inValue.request = request;
            WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestResponse retVal = ((WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService)(this)).DoNormalEnquiryStreamTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestResponse> WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService.DoNormalEnquiryStreamTestAsync(WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestRequest request) {
            return base.Channel.DoNormalEnquiryStreamTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestResponse> DoNormalEnquiryStreamTestAsync(WealthGrowthCreditVerification.CompuscanClient.NormalEnqRequestParamsType request) {
            WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestRequest inValue = new WealthGrowthCreditVerification.CompuscanClient.DoNormalEnquiryStreamTestRequest();
            inValue.request = request;
            return ((WealthGrowthCreditVerification.CompuscanClient.NormalSearchStreamService)(this)).DoNormalEnquiryStreamTestAsync(inValue);
        }
    }
}
